version: "3.9"
services:
  redis:
    container_name: redis_keyspace_events_node_demo
    image: "redis/redis-stack:edge"
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      - REDIS_ARGS=""
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
